### ISSUE TITLE
Possible Valkurm Emperor Spawn Issue

### ISSUE THREAD

**Issue by Moonlegend88** [Demiurge-DSP/feedback-and-info#11]
**Feedback or issue :**  

I noticed the last 2 times I went to hunt VE he popped after killing all the flies in area, along with PH, not sure if this is intended or not but figured id let you know.

- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**

**Comment by TeoTwawki** [comment]
Not sure whats possibly wrong here? Anytime an NM isn't on cooldown and a placeholder is dev to repop. the NM normally has a chance to pop. Sometimes darkstars placeholders match retail (leaping lizzy) and sometimes not (jaggedy eared jack has extra ones). For reference, other than increasing the spawn rate and decreasing the cooldown, we use what darkstar has,
