### ISSUE TITLE
Sozu Rogberry pop spot

### ISSUE THREAD

**Issue by Moonlegend88** [Demiurge-DSP/feedback-and-info#13]
I spawned Sozu Rogberry earlier and I was killed, RIP. He despawned and after several hours the ??? still didn't respawn.

- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**

**Comment by tb1** [comment]
After the server restart, the ??? did come back.

**Comment by TeoTwawki** [comment]
It may have problems respawning after a failed battle though, I haven't checked yet. beyond teh code looking like it should work:

```lua
function onMobDespawn(mob)
    GetNPCByID(SOZU_ROGBERRY_QM):updateNPCHideTime(FORCE_SPAWN_QM_RESET_TIME);
end;
```
@Moonlegend88 are we sure he actually despawned rather than wandering off to some wrong position? He doesn't look like he's set up to despawn.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/4627

I didn't even see it

**Comment by TeoTwawki** [comment]
Hotfix'd
