### ISSUE TITLE
Cactrot Rapido

### ISSUE THREAD

**Issue by Moonlegend88** [Demiurge-DSP/feedback-and-info#14]
This NM in Eastern Altepa Desert located around G-9 POS -45.000,0.050,-204.000
you can engage and attack but the target remains unclaimed and doesn't attack back.

- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**

**Comment by TeoTwawki** [comment]
Will fix in tomorrow's maint. Sort of. He'll be enagable. In retail you have to link him onto another cactaur in the area.

**Comment by Moonlegend88** [comment]
5am? at least you can make Pancakes before sleep.

**Comment by Moonlegend88** [comment]
If he wasn't broken he would have wrecked my shit cause I'm not currently at capped skill, need to stop poking random NMs

**Comment by TeoTwawki** [comment]
I forgot to commit it before the most recent maint but the work is done and its in the next one for sure

**Comment by TeoTwawki** [comment]
last maint took care of this
