### ISSUE TITLE
Y BRD NO WORK!

### ISSUE THREAD

**Issue by tb1** [Demiurge-DSP/feedback-and-info#15]
**Feedback or issue :**  

Not sure if this is a DSP issue, a client version issue, a TB1 is dumb issue, or a Teo hates TB1 issue.

Client: 30180203_1
ECV: 30171205_0

Quest: The Old Monument
http://ffxiclopedia.wikia.com/wiki/The_Old_Monument
https://www.bg-wiki.com/bg/The_Old_Monument

## Long Version
Talked to Mertaire (Lower Jeuno I-8), he starts by sound a little like Bill Burr talking about how woman suck, then goes all emo about how his girlfriend left him.  Talked to him a few times just to be sure.

Talked to the hot mithra bar wench Bki Tbujhja, she talks about some lame ass poetry in Buburimu, and how she wants to be loved.  She also hints at how she wants to jump Mertaire's bones.  Talked to her a few times to be sure too.

Even talked to some other dude in the bar who's like "Leave that pathetic loser alone" (in reference to Mertaire).

So I go to Buburimu, find the song runes the bar wench was talking about.  Check them out, and nothing happens (expected some old lame ass stalker bard to appear and talk about the power of music).  Try to download the song to my parchment so I can share it on napster, still no luck (DRM maybe?).

Anyway, can't progress to BRD quest.

## TL;DNR
- Talked to Mertaire 
- Talked to Bki Tbujhja
- Check song runes, nothing happened.
- This shit is b0rked for me.

## Obligatory Image

![8681](https://user-images.githubusercontent.com/3310503/36643967-3fe30be0-1a10-11e8-8c14-80ff3cb75071.jpg)

- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**

**Comment by EpicTaru** [comment]
I want more issues like this for obligatory images like that!

**Comment by EpicTaru** [comment]
And when I've had to help ppl with that issue, I had then to back to the bar in jeuno and re-talk to ppl there. If that didn't fix it, it was because of the version mismatch

**Comment by tb1** [comment]
After the update, and fucking around a few times with the quest NPCs, the CS finally triggered.  I also disabeld enternity just incase there was some stupid race condition causing it.

**Comment by TeoTwawki** [comment]
another issue resolved by psychic powers :+1:
