### ISSUE TITLE
PLD AF

### ISSUE THREAD

**Issue by tb1** [Demiurge-DSP/feedback-and-info#16]
**Feedback or issue :**  

http://ffxiclopedia.wikia.com/wiki/A_Boy%27s_Dream

The part where you have to fish up a monster doesn't appear to be working correctly, or has an insanely low chance.

The DSP code for the quest looks to be implemented.(https://github.com/DarkstarProject/darkstar/blob/cb9fe3437ad6206d0104c15e83199bc612978f93/scripts/zones/Northern_San_dOria/npcs/Ailbeche.lua) 

And the fishing code for that specific fish should be in DSP (https://github.com/DarkstarProject/darkstar/pull/3783)

I figured after about 40 casts, I would have seen something other than "You didn't catch anything.".

Not sure if I am just being an impatient twat, or something is not functioning properly in the rest of the fishing code.

- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**

**Comment by TeoTwawki** [comment]
I think I recall a pr for that that didn;' get fixed so it didn't get merged..brb

**Comment by TeoTwawki** [comment]
Hmm can't find it. I thought someone said it was busted after that and tried to fix it. Probably yet another case of someone talking in discord without opening anything on DSP's github.

I'll see if I can figure out why nothing bit for you when I can. It sounds to *fishy* to just be bad luck.

###### *I had to*

**Comment by EpicTaru** [comment]
🐟

**Comment by TeoTwawki** [comment]
Update:
The NM has no spawn position in darkstar..
```sql
INSERT INTO `mob_spawn_points` VALUES (17396141,'Odontotyrannus','Odontotyrannus',8091,0,0,0,0);
```
0,0,0 = cannot be spawned.

This will be fixed in the next maint.

**Comment by TeoTwawki** [comment]
p.s.
I'll also be on after maint to test it myself and will make sure you get your clear

**Comment by TeoTwawki** [comment]
been looking for you, when you are available let me know so I can go with you for that NM and make sure you get your fish
