### ISSUE TITLE
Crafting Bug

### ISSUE THREAD

**Issue by Moonlegend88** [Demiurge-DSP/feedback-and-info#18]
**Feedback or issue :**  

Upon receiving a break on a craft with 2 or more required mats it seems to lock one of them in inventory, at times you don't seem to lose the items that become locked, if its a crit break, Zoning seems to be the only way to fix.

- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**

**Comment by TeoTwawki** [comment]
have opened an issue in DSP about it https://github.com/DarkstarProject/darkstar/issues/4647

will emergency maint after fix happens

**Comment by TeoTwawki** [comment]
main completed
