### ISSUE TITLE
Daily conquest tallies and outpost warps

### ISSUE THREAD

**Issue by davismj** [Demiurge-DSP/feedback-and-info#21]
**Feedback or issue :**  

Weekly conquest tallies, especially on a small server, are just a time sink mechanic, forcing you to wait a week before you can try for that new outpost or buy that rank 1 only item. 

On the other hand, the concept of outpost warps were well designed. Every player is required to make the run to Jeuno before thay can Qufim warp, farm Kazham keys before they can Yuhtunga/Yhoator warp, traverse Ranguemont Pass before they can Beaucedine / Xarcabard warp. Additionally, they are required to either xp in that specific area or hope someone of their faction does to get the option of a supplies quest.

Making all OPs open is not a QoL change but a straight easymode gameplay nerf. **I recommend that we shorten conquest tallies to daily and require supplies quests for OP warps.** This will remove the time sink and increase QoL without dumbing the game down.

- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**

**Comment by davismj** [comment]
i'd still like to see this. capturing a zone and completing the supply run is a gameplay mechanic. its nice to have it all done for you, but it makes the game a little less fun. i dont want to remove gameplay mechanics.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues/6068

one example of many reasons I cannot do this currently.
