### ISSUE TITLE
Level Cap Promyvion

### ISSUE THREAD

**Issue by davismj** [Demiurge-DSP/feedback-and-info#22]
**Feedback or issue :**  

The content was designed to be interesting at a level 30 cap. It's boring otherwise. Considering it's super optional, I recommend we bring the cap back.

- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [ ] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [ ] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**

**Comment by TeoTwawki** [comment]
intended: battlefields capped zone not

unfortunately dsp kinda broke that atm..

**Comment by davismj** [comment]
why not just cap it all then? to make the run faster?

**Comment by TeoTwawki** [comment]
higher lv was added content in zone, was mainly for lb 80-85, but I have an at 75 use for it

**Comment by TeoTwawki** [comment]
no spoilers

**Comment by davismj** [comment]
adding post 75 content to pre 75 dungeons is the worst thing to happen to this game

**Comment by TeoTwawki** [comment]
oh I'd argue trying to up-level is worse
*stares at itemLevel Abyssea*

**Comment by TeoTwawki** [comment]
but really. 75-80 is only a 5 lv gap. And I already have an extensive list of area's I need to delevel @_@ 

https://github.com/Demiurge-DSP/feedback-and-info/issues/5

**Comment by davismj** [comment]
still voting for the level cap
