### ISSUE TITLE
Set MINING_RATE to 100%

### ISSUE THREAD

**Issue by davismj** [Demiurge-DSP/feedback-and-info#23]
**Feedback or issue :**  

"You were unable to mine anything" is Japanese for "I have just flushed your time down the toilet." IMHO, MINING_RATE as well as other HELM rates should be increased to 100%. 

With said change, the "Your pickaxe breaks" message would disappear. To compensate, we can buff the break rate to 50%, up from 33%. I could work the math out if necessary, but in general this should mean that you will get the same overall yield per stack of pickaxes, but it will cut the time requirement in half.

- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**

**Comment by TeoTwawki** [comment]
Resolution:


- [x] gear that grants bonuses to helm activities will modify both tool breaks *and* item rates. previously this only modified break rate. **nothing will ever modify the rates to either 0 or 100% ever. deal wid it.** :stuck_out_tongue: 

- [?] modify base break rate, breaks have not been eliminated but a full set of gear can bring it close to a 1/10 rate

- [!] modify base item find rate, finding nothing has not been eliminated but a full set of gear can bring it to between 5% and 10% 

- [o] you can click the boxes with you mouse. it takes less than a 1 second for your finger to move that far. everybody got time for that. But I know we have ~~no mouth and must scream~~ memes and we must share.

![memes everywhere](https://user-images.githubusercontent.com/6871475/37936938-84633d5e-3125-11e8-8e1c-5e5ee21e506b.gif)

**Comment by davismj** [comment]
@EpicTaru

**Comment by EpicTaru** [comment]
@davismj ¯\_(ツ)_/¯

**Comment by TeoTwawki** [comment]
@EpicTaru hi there you look like you lost and arm, is this your arm?

 \\

you should have a reattach that by escaping the slash character with another slash. :grin:
