### ISSUE TITLE
List of ToAU Fish to sell via AH Bot/Fishing Guild Merchant

### ISSUE THREAD

**Issue by RavenTactics** [Demiurge-DSP/feedback-and-info#24]
**Feedback or issue :**  More like a workaround?

Fishing functions in a way currently. This idea is a work in progress and is intended to allow vanilla fishing to still be a viable option for those that want to fish, but give an option for stocking a guild merchant (sell only/no buying perhaps?) and/or the AH bot, to help sell fish to crafters (mostly cooking). 

Notes: 
- I believe that I have the full ToAU fish (http://www.great-blue.jp/?lng=en), minus the ones that are really only used for quests like inside the belly. 
- The current downside is I don't have an active retail account to check how much they buy/sell to an NPC for so I don't have prices for buy/sell to offer at this time.  
- I'd have to log into another server to try and see what/if anything the guild NPCs buys/sells for in case of an imbalance. 

Fish Name		Craft Benefit(s)
---------------------------------------------
Ahtapot ..................... 2: Alchemy, Cooking
Alabaligi .................... Cooking
Betta ........................... Woodworking
Caedarva Frog ......... 2: Alchemy, Cooking
Denizanasi ................. Alchemy
Dil ................................. Cooking
Hamsi .......................... 2: Cooking, Synergy
Istakoz ........................ Cooking
Istavrit ......................... Alchemy
Istiridye ....................... 2: Alchemy, Cooking
Kalamar ......................	2: Alchemy, Cooking
Kalkanbaligi ............. Cooking
Kaplumbaga ............ Cooking
Kayabaligi ................ Woodworking
Kilicbaligi .................. Cooking
Lakerda ...................... Cooking
Mercanbaligi ........... Cooking
Morinabaligi ........... Cooking
Rhinochimera ......... 2: Bone, Cooking
Tiny Goldfish ........... Woodworking
Uskumru ................... Cooking
Yilanbaligi ................ Cooking

- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  
- [x] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**

**Comment by TeoTwawki** [comment]
Makes issue for discussing bot > watches it go largely unused > dies inside

I'd rather not use the ToAU versions. If I have the regular version I can look them up easier to fix whats missing because we actually should be able to get those but I know some we can't, whereas with ToAU we aren't supposed to yet so it just turns up "everything is not available". Pls suggest items in teh existing catch all for suggesting items.
