### ISSUE TITLE
New Drop Request + Mob Ajustment.

### ISSUE THREAD

**Issue by MoonlegendXI** [Demiurge-DSP/feedback-and-info#25]
**Feedback or issue :**  

Could you possibly add Orichalcum Ore to some 70+ mobs or even a custom mob, Talking Turtle perhaps? http://ffxiclopedia.wikia.com/wiki/Orichalcum_Ore

- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**

**Comment by TeoTwawki** [comment]
> NM Golem now have a high chance to drop Orichalchum Ore. Enkidu now have a low chance to drop Platinum Ore. Darksteel Golem now have a low chance to drop Darksteel Ore.

this happened and I forgot to close the issue
