### ISSUE TITLE
Incorrect loot table Rock Lizard (lvl 5-8)

### ISSUE THREAD

**Issue by RavenTactics** [Demiurge-DSP/feedback-and-info#27]
**Feedback or issue :**  It looks like "Added Squamous Hide to Drachenlizard drop #4168" (https://github.com/DarkstarProject/darkstar/pull/4168) somehow made it's way into the  Rock Lizards (lvl 5 - 8 mob) loot table.   I think this was an intentional drop added to standard DS server, but it may be an inappropriate item (at this time) for Demiurge. 

REPLACE THIS TEXT

- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**  

**Date**: May 25, 2018
**Incorrect Mob**:  Rock Lizard (lvl 5-8)
**Zone**: Dangruf Wadi 
**POS|!where**:  J-13 |  Compass: X: -79 Y: 4 Z: -203 (19)
**Item**: Squamous Hide (http://ffxiclopedia.wikia.com/wiki/Squamous_Hide)
**Correct Mob**:  Drachenlizard | 93-94 | North Gustaberg (S)

![image](https://user-images.githubusercontent.com/37428609/40534692-c3e53b8e-5fbb-11e8-833a-19ce36312522.png)

**Comment by TeoTwawki** [comment]
@davismj thanks for fixing that in dsp :+1:
