### ISSUE TITLE
Woodworking Vender not Trading

### ISSUE THREAD

**Issue by Jankin01** [Demiurge-DSP/feedback-and-info#29]
Chaupire (Woodworking Vender) in the Woodworking guild is refusing to trade with me, the other vender (Cauzeriste) is trading as normal, I've tried to zone, relog, I have the up-to-date Darkstar ver.

- [X] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [X] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [X] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [X] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**

**Comment by TeoTwawki** [comment]
forwarded to derpsee so that someone may know to fix in case I don't get to it fast enough

**Comment by TeoTwawki** [comment]
per shelby's checking:
> [Not a bug, the guildshop (5132) has no daily increase set for items in the shop list. If you sell a shop item you can reload the shop and find that it is that item is in stock.Recommend to close or decide that guildshops should have a daily increase set for more items. ](https://github.com/DarkstarProject/darkstar/issues/5443#issuecomment-447604950)

**Comment by TeoTwawki** [comment]
if the issues was misunderstood let me know
