### ISSUE TITLE
Dead with 1 HP remaining

### ISSUE THREAD

**Issue by tb1** [Demiurge-DSP/feedback-and-info#3]
- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**  

**Feedback or issue :**  

When getting 1 shot by Final Sting (in crawler's nest), HPs show 1, yet I'm still dead.

In the screenshot, Ked (top left) is the one who got 1 shot.  Everyone else sees him as having 1 HP.  Not a big issue, but does make cureplease go mental, and I could see it causing problems/confusion in a proper party situation.

![screenshot_2018-02-11_23-37-47](https://user-images.githubusercontent.com/3310503/36085676-b03a56c8-0f84-11e8-938f-1aae33189cce.png)

**Comment by tb1** [comment]
Ked is unable to move, and is actually dead (hence the back to homepoint dialog)

**Comment by tb1** [comment]
Looks like it's not just when 1 shot, got killed normally and the same thing happened.  1 HP displayed.  Can still raise normally, just a little odd and confusing at times.

**Comment by TeoTwawki** [comment]
Cause has been reported it to Darkstar's tracker.

**Comment by TeoTwawki** [comment]
Just did a quick maint to get the correction in, its fixed now.
