### ISSUE TITLE
Request to add a !GetCraftLevel command

### ISSUE THREAD

**Issue by RavenTactics** [Demiurge-DSP/feedback-and-info#32]
**!GetCraftLevel :** to request the server value of the actual crafting level to the tenth degree.  

This is a QoL request. But it will be so nice to see where I actually stand. I.E. 97 vs. 97.3 

- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**

**Comment by Reignbow** [comment]
I second this request.  It would be super nice to have. ^-^

**Comment by TeoTwawki** [comment]
I'll add this soon.

**Comment by TeoTwawki** [comment]
![image](https://user-images.githubusercontent.com/6871475/54164683-e48d5800-4433-11e9-8574-0df43cf99823.png)

**Comment by TeoTwawki** [comment]
completed
