### ISSUE TITLE
Event moogle gave me BCNM status, and it's stuck.

### ISSUE THREAD

**Issue by tb1** [Demiurge-DSP/feedback-and-info#36]
**Feedback or issue :**  

I dun b0rked it.

I talked to moogle outside of sandy (West Ronfaure), he told me about a stinky pussy.  I went to go pound her, but she won't let me touch her.  Now I can't get rid of the BCNM status.

This is on Ned and Jed.

I tried zoning, changing jobs, creating a party with someone who doesn't have BCNM status and killing her with them, none of it works.  It's like an STD, and I think I need some antibiotics.

- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**  

[x][x][x][x][x][x][x][x][x]
[x][x][x][x][x][x][x][x][x]
[x][x][x][x][x][x][x][x][x]

**Comment by TeoTwawki** [comment]
huh.. be right there to check this

**Comment by TeoTwawki** [comment]
For some reason the effect wasn't applied the way I originally intended after the system of file catching came in from upstream. This may be from something I missed during merge.

Removed application of cap from moogles for now and removed status from affected players.
