### ISSUE TITLE
2-3 Mission [Bastok Home Nation] Sandy > Windy

### ISSUE THREAD

**Issue by AppleCrumble1** [Demiurge-DSP/feedback-and-info#37]
**Feedback or issue :**  

ver 30210706_2   
Character: Appleshop
Time of happening: around 6pm ish BST [UK Time]
Position: BCNM Balga's Dais, Windy/Basty

2-3 Mission [Bastok Home Nation] Sandy > Windy
Completed the black dragon fight on my 6 chars, all but 1 could speak to Melek then Naji and achieve Rank 3.
Appleshop is unable to speak to Melek she just is unresponsive or Naji who knows nothing of the Mission, char has Black dragon slayer as title but has 0 KI, either the Key Item Kindred crest or Key Item Kindred Report in the KI temp or perm lists.
returned to the BCNM in Balga's Dais and it acts unresponsive.

yes i was multiboxing, yes shit happens when we do this, sorry.

- [ x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x ] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [ x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x ] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**

**Comment by TeoTwawki** [comment]
Fixed by walking character back through steps allll they way back at warchief vatgit
