### ISSUE TITLE
Multi boxing issues Maat fight entrance 

### ISSUE THREAD

**Issue by AppleCrumble1** [Demiurge-DSP/feedback-and-info#38]
**Feedback or issue :**  

ver 30210706_2
6 accounts on multibox in same  party in same area, horalis peak. Shattering stars  maat fight attempts.
Acc1 traded blm test entered, preceeded to win bcnm then left zone with warp after victory. Switched to access and noticed bcnm status still in effect. Clicked burning circle offered blm maat fight as an option without trading test. 

This occurred for all 5 remaining accounts.
Zoned, logged all 6 off waited 10 mins, logged back on and bc status still there, waited iver 30 mins and bcnm status still on. Clicking burning circle still gave bkm maat fight option without trading test. When tried to trade test said you must wait longer for this.

Sprinkles was trader
Appleshop, Brownie, Chocolate, Cake and Caramel were the other characters. Happened at Horlais peak around 4am bst(British Summer Time)

- [x ] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [ x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [ x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x ] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**

**Comment by TeoTwawki** [comment]
Removed bad status, opening an issue with upstream as I don't see how this is possible yet here we are.
