### ISSUE TITLE
ZOMG! Won't let me get chariot band!

### ISSUE THREAD

**Issue by tb1** [Demiurge-DSP/feedback-and-info#6]
- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**  

**Feedback or issue :**  

![jed_2018 02 16_202317](https://user-images.githubusercontent.com/3310503/36337617-75308c1a-1357-11e8-911e-85269fbc6904.png)

I don't meet the requirements to get a chariot band.

Some of the obvious:
  - Hi! My name is Jed, I'm an ffxiaholic.
  - Yes I am a Galka from sandy, I realize this was a poor choice.
  - Yes I have enough conquest points (54,294)
  - Yes I tried disabling enternity just in case.
  - Yes a conquest tally has happened since I got my last one (multiple have)
  - No I do not have a chariot band, empress band or emperor band in my possession.
  -  Previously had a chariot band, dropped it to get a new one (since recharging was broken on other servers).  I did this procedure a few times here already without issue.

I can't think of any more obvious questions that might be asked.

**Comment by TeoTwawki** [comment]
what day/time was your last ring get / ring recharge, before i go turn that gate guard upside down and shake him for you till he drops a ring?

**Comment by tb1** [comment]
I don't remember, I've been crafting alot so haven't been using it much.  If you want to delay till tomorrow just in case, I'm fine with that, I can come and close it if it is just me being a noob.
